#!/usr/bin/env python

import subprocess
import signal
import sys
from apscheduler.schedulers.blocking import BlockingScheduler


def handle_int(sig, frame):
    sys.exit(0)


def drink_water():
    print('Drink water')
    subprocess.run(['mpg123','-n', '200', '/home/yuqyda/Music/water.mp3'])
    subprocess.run(["notify-send", "Drink Water"])


if __name__ == '__main__':
    signal.signal(2, handle_int)
    sched = BlockingScheduler()
    sched.add_job(drink_water, 'interval', minutes=20)
    sched.start()
